
-- DROP TABLES AND SEQUENCES
DROP TABLE PRESCRIPTION CASCADE CONSTRAINTS;
DROP TABLE LAB_TEST_RESULT CASCADE CONSTRAINTS;
DROP TABLE MEDICAL_RECORD CASCADE CONSTRAINTS;
DROP TABLE BILLING CASCADE CONSTRAINTS;
DROP TABLE APPOINTMENT CASCADE CONSTRAINTS;
DROP TABLE PHARMACIST CASCADE CONSTRAINTS;
DROP TABLE NURSE CASCADE CONSTRAINTS;
DROP TABLE DOCTOR CASCADE CONSTRAINTS;
DROP TABLE PATIENT CASCADE CONSTRAINTS;
DROP TABLE "USER" CASCADE CONSTRAINTS;

DROP SEQUENCE user_seq;
DROP SEQUENCE patient_seq;
DROP SEQUENCE appointment_seq;
DROP SEQUENCE billing_seq;
DROP SEQUENCE prescription_seq;
DROP SEQUENCE medical_record_seq;
DROP SEQUENCE lab_test_result_seq;

-- INFORMATION QUERIES

-- 1. Patients with doctor and appointment date
SELECT P.FullName AS PatientName, D.FullName AS DoctorName, A.DateAndTime
FROM PATIENT P
JOIN APPOINTMENT A ON P.PatientID = A.PatientID
JOIN DOCTOR D ON A.UserID = D.UserID;

-- 2. Unpaid bills with patient names 
SELECT P.FullName, B.PaymentAmount, B.PaymentStatus
FROM BILLING B
JOIN APPOINTMENT A ON B.AppointmentID = A.AppointmentID
JOIN PATIENT P ON A.PatientID = P.PatientID
WHERE B.PaymentStatus = 'Unpaid';

-- 3. Prescriptions for a specific patient
SELECT P.FullName, R.MedicationName, R.Dosage, R.IssuedDate
FROM PRESCRIPTION R
JOIN APPOINTMENT A ON R.AppointmentID = A.AppointmentID
JOIN PATIENT P ON A.PatientID = P.PatientID
WHERE P.FullName = 'John Doe';

-- 4. Lab test results
SELECT P.FullName, L.Diagnosis, L.Notes
FROM LAB_TEST_RESULT L
JOIN MEDICAL_RECORD M ON L.MedicalRecordID = M.MedicalRecordID
JOIN PATIENT P ON M.PatientID = P.PatientID;

-- ROW LIMITATION

SELECT * FROM APPOINTMENT ORDER BY DateAndTime DESC FETCH FIRST 5 ROWS ONLY;
SELECT FullName, BloodType FROM PATIENT FETCH FIRST 10 ROWS ONLY;
SELECT PaymentAmount, PaymentMethod FROM BILLING ORDER BY PaymentAmount DESC FETCH FIRST 3 ROWS ONLY;
SELECT FullName, AppointmentsCompleted FROM DOCTOR FETCH FIRST 4 ROWS ONLY;

-- SORTING

SELECT FullName, DOB FROM PATIENT ORDER BY FullName ASC;
SELECT FullName, Specialization FROM DOCTOR ORDER BY Specialization;
SELECT * FROM APPOINTMENT ORDER BY Status;
SELECT * FROM BILLING ORDER BY PaymentAmount DESC;

-- CONDITIONS

SELECT * FROM PATIENT WHERE FullName LIKE 'A%';
SELECT * FROM DOCTOR WHERE Specialization = 'Cardiology' OR Specialization = 'Neurology';
SELECT * FROM PATIENT WHERE DOB > DATE '2000-01-01' AND BloodType = 'A+';
SELECT * FROM APPOINTMENT WHERE Status = 'Completed' OR Status = 'Cancelled';

-- STRING FUNCTIONS

SELECT UPPER(FullName) AS NameUpper FROM PATIENT;
SELECT SUBSTR(FullName, 1, 3) AS NameAbbrev FROM DOCTOR;
SELECT FullName, LENGTH(Address) AS AddressLength FROM PATIENT;
SELECT FullName || ' <' || EmailAddress || '>' AS Contact FROM PATIENT;

-- ROUND/TRUNC

SELECT ROUND(PaymentAmount, -1) AS RoundedPayment FROM BILLING;
SELECT TRUNC(PaymentAmount, 1) FROM BILLING;
SELECT ROUND(TO_NUMBER(Dosage)) AS RoundedDosage FROM PRESCRIPTION;
SELECT TRUNC(TO_NUMBER(Duration)) AS TruncatedDuration FROM PRESCRIPTION;

-- DATE FUNCTIONS

SELECT SYSDATE AS Today FROM DUAL;
SELECT FullName, FLOOR(MONTHS_BETWEEN(SYSDATE, DOB) / 12) AS Age FROM PATIENT;
SELECT * FROM APPOINTMENT WHERE TRUNC(DateAndTime, 'IW') = TRUNC(SYSDATE, 'IW');
SELECT BillingID, SYSDATE - PaymentDate AS DaysAgo FROM BILLING WHERE PaymentDate IS NOT NULL;

-- AGGREGATES

SELECT COUNT(*) AS TotalPatients FROM PATIENT;
SELECT AVG(PaymentAmount) AS AvgPayment FROM BILLING;
SELECT MAX(TO_NUMBER(Dosage)) AS MaxDosage FROM PRESCRIPTION;
SELECT MIN(FLOOR(MONTHS_BETWEEN(SYSDATE, DOB) / 12)) AS MinAge FROM PATIENT;

select * from PATIENT;
select * from DOCTOR;
select * from "USER";
UPDATE APPOINTMENT set APPOINTMENTID = 3 where APPOINTMENTID = 401;
